name: Auto Open Pull Request

on:
  push:
    branches:
      - 'feature/*'

jobs:
  open-pr:
    runs-on: ubuntu-latest

    steps:
      # Verifica o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3      
