name: Auto PR for feature branches

on:
  push:
    branches:
      - feature/*

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código do repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar o Git para o autor da PR
    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    # Criar a PR automaticamente
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.TOKEN }}
        source-branch: ${{ github.ref_name }} # Nome da branch atual
        target-branch: develop               # Nome da branch de destino
        title: "Auto PR - ${{ github.ref_name }} -> develop"
        body: |
          Esta PR foi aberta automaticamente a partir de um commit na branch `feature/${{ github.ref_name }}`.
        branch: auto-pr/${{ github.ref_name }} # Branch temporária para criar a PR
