name: Auto PR for feature branches

on:
  push:
    branches:
      - feature/*

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        source-branch: ${{ github.ref_name }}
        target-branch: develop
        title: "Auto PR - ${{ github.ref_name }} -> develop"
        body: |
          Esta PR foi aberta automaticamente a partir de um commit na branch `feature/${{ github.ref_name }}`.
        branch: auto-pr/${{ github.ref_name }}
        always-create: true
