name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - uses: actions/checkout@v3

      # 2. Instalar dependências e build da aplicação localmente
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Certifique-se de usar a versão correta

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      # 3. Enviar a pasta 'dist' para o servidor via SCP
      - name: Copy 'dist' folder to remote server via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ''
          source: './dist'
          target: ${{ secrets.TARGET }}
          debug: true
          timeout: 120s # Increase timeout to 120 seconds

      # 4. Executar comandos no servidor remoto (se necessário)
      - name: Executing remote command via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ secrets.TARGET }}
            # Adicione aqui comandos necessários após o envio
